name: Deploy on server via docker

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update docker container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${‎{ secrets.DEPLOY_HOST }‎}
          username: ${‎{ secrets.DEPLOY_USERNAME }‎}
          key: ${‎{ secrets.DEPLOY_KEY }‎}
          port: 22
          script: |
            cd ~/home/java-team2/deploy
            ./service-update.sh ${‎{ vars.DOCKER_CONTAINER_NAME }‎}
          
        
